### ISSUE TITLE
Download and process TRI data

### ISSUE THREAD

**Issue by MAKassien** [Spatiotemporal-Exposures-and-Toxicology/amadeus#4]

**Comment by sigmafelix** [comment]
Up-to-date `calc_tri` is pushed to `init_spinoff` branch along with its tests. The current version considers stack and fugitive air by compounds and the units (pounds or grams) were unified to kilograms.

**Comment by MAKassien** [comment]
Great, thanks Insang! I will review the new version and give you my thoughts. And yes, I think by chemical is the right way to split the data.

**Comment by sigmafelix** [comment]
Do we have a list of TRI covariate names? We are using the covariate names in NRT-AP-Model_Covariates spreadsheet, where TRI covariates were not specified. Since the chemical codes are strings in varying lengths, we will use "long names" for these covariates. My initial thought is to use `"EMI_STACK/FUGTV_[chemical_code]_[buffer_size]".

**Comment by MAKassien** [comment]
We don't have a list yet, but the naming system you are proposing sounds reasonable to me. Since we're talking order of >1000 different chemicals, maybe we can make a separate reference spreadsheet with chemical code, name, and chemical category, in case we decide to select only certain chemicals or to group them by category later

**Comment by sigmafelix** [comment]
@MAKassien Yes, I think it is time to update the covariate list. I will add a worksheet to the covariate list with TRI chemical codes and full names as they are recorded. We could talk more about classification later.

**Comment by MAKassien** [comment]
I've finished reviewing all the TRI functions and everything checks out. Thanks for the hard work @sigmafelix! We should be good to close this issue and proceed to covariate calculation 😃

**Comment by sigmafelix** [comment]
I computed TRI variables (3,468 variables from 1, 10, and 50 kilometers radius) and saved it in our team project output directory. Treating `NA` needs to be discussed in the next meeting. Thank you for your feedback @MAKassien !

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@sigmafelix @MAKassien 
We can discuss NA/zeros, but briefly:
1. TRI variables based on SEDC should not have an NA because distance is always defined. If there are NA in SEDC then we need to look at the distance matrix and make sure that nothing weird is happening there. 
2. Other variables should be handles on a case-by-case basis. Typically if NA is less than 5% then a simple linear interpolation is reasonable. 
3. We should see if there are cases for real zeros - those are of course fine to include

**Comment by sigmafelix** [comment]
@Spatiotemporal-Exposures-and-Toxicology @MAKassien 
Most (I believe all of) `NA`s come from the different chemicals by emission sources. `process_tri` transforms the input long table into a wide table, which results in many `NA`s as the long table records the chemicals emitted at each location. Basically we can think of `NA`s are true zeros as they were not recorded in the original EPA data.
